image: Visual Studio 2017

os: unstable

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

skip_branch_with_pr: true # Do not build feature branch with open Pull Requests
max_jobs: 1

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - npm ci

build_script:
  - npm run test
  - npm run test:e2e
  - npm run lint
  - npm run build

test: off
