matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: 10
    - os: linux
      services: docker
      language: generic

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        electronuserland/builder:wine-chrome \
        /bin/bash -c "yarn test && yarn lint && yarn build"
    else
      yarn test
      yarn lint
      yarn build
    fi
