language: node_js

node_js:
  - 10.4.1

matrix:
  allow_failures:
    - os: linux
  fast_finish: true

os:
  - linux
  - osx

before_script:
  - ./scripts/travis-xvfb.sh

script:
  - npm run test
  - npm run lint
  - npm run build
