name: snapcraft

on:
  workflow_dispatch:
    inputs:
      manual_name:
        required: true
        description: 'Release number to publish (without v prefix)'
        default: '0.0.0'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      SNAP_RELEASE_NAME: ${{ github.event.inputs.manual_name || github.event.release.name }}
    steps:
      - name: Download .snap artifact
        uses: dsaltares/fetch-gh-release-asset@0efe227dedb360b09ea0e533795d584b61c461a9 # 0.06
        with:
          repo: ipfs/ipfs-desktop
          version: tags/v${{ env.SNAP_RELEASE_NAME }}
          file: ipfs-desktop-${{ env.SNAP_RELEASE_NAME }}-linux-amd64.snap
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Snapcraft
        uses: snapcore/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40 # 1.2.0
        with:
          store_login: ${{ secrets.SNAP_STORE_LOGIN }}
          snap: ipfs-desktop-${{ env.SNAP_RELEASE_NAME }}-linux-amd64.snap
          release: stable
